---
title: "Introducción al análisis de secuencias NGS"
subtitle: 'Curso Genética y Genómica en Producción Animal'
author:
 name: Dr. José A. Gallardo, Dr(c) Margarita Rivera.
 affiliation: Pontificia Universidad Católica de Valparaíso
 email: <jose.gallardo@pucv.cl>
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
    code_folding: hide
  word_document: default
  pdf_document: default
---

<style>
#TOC {
  color: black;
  font-familiy: Calibri;
  font-size: 14px;
  border-color: #708090; 
}
body {
   color: black;
   font-familiy: Calibri;
}

pre {
  color: black;
  background-color: #F8F8FF;
}
# header {
  color: #800000;
  font-familiy: Calibri;
  background-color: #F5F5F5;
  opacity: 0.8;
  font-size: 16px;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## INTRODUCCIÓN

El paso de alineación de secuencias se considera una parte integral que contribuye directamente a las identificaciones de ADN, ARN o proteínas (Pham-Quoc, Kieu-Do, & Thinh, 2019). El problema del mapeo de reads consiste en ubicar o alinear dentro de un genoma de referencia previamente secuenciado los millones de reads para luego ensamblarlas a un nuevo genoma (Bak, Bodziony, Migdałek, Pareek, & Żukowski§, 2020). Esta carga de trabajo se la realiza con diferentes enfoques de alineación, sin embargo, al igual que cualquier software, cada enfoque presenta diferentes formas de ejecución y consecuentemente de análisis.
Como se explicó, para averiguar el nivel de similitud entre una gran cantidad de datos genómicos se presenta un desafío computacional para los softwares de alineación y por ello, se han desarrollado varios programas que ayudan en esta tarea, como lo son, BWA (Li & Durbin, 2009), Bowtie 2 (JHU, 2016) y otros, cuya función principal es hacer coincidir secuencias cortas provenientes de NGS con secuencias de referencia (Bak, Bodziony, Migdałek, Pareek, & Żukowski§, 2020). De hecho, BWA es un software muy popular para fines de alineamiento, debido a su compatibilidad con datos de Illumina y la integración de distintos algoritmos de alineamiento con mayor rendimiento para reads de distintas longitudes (Li & Durbin, 2009).

En este tutorial se realiza el alineamiento 

### FORMATO SAM


### FORMATO BAM


### SOFTWARES DE BIOINFORMÁTICA

**BWA**





## PRÁCTICA UNIDAD 3 - SUBTÓPICO 2.2

**ALINEAMIENTO DE SECUENCIAS**

### 1 - CONECTAR A SERVIDOR POMEO

Conecte al servidor pomeo usando la siguiente dirección IP: **200.54.220.141** puerto 22.

Ese el software PuTTy y las claves de acceso dadas en la primera clase.

### 2 - CONFIGURAR BIOCONDA E INSTALAR SOFTWARES PARA ANÁLISIS

Para configurar el canal bioconda se debe ejecutar el siguiente comando

    conda config --add channels bioconda
    
Para la instalación de los software proceda a ejecutar los siguientes comandos en la terminal:

    conda install -c bioconda bwa

### 3 - DESCARGA DEL GENOMA DE REFERENCIA

Crear una carpeta de trabajo denominada alineamiento
Descargar el genoma de referencia del organismo ____

### 4 - INDEXACION DEL GENOMA DE REFERENCIA



### 5 - ALINEAMIENTO


**Alineamiento de lecturas contra un genoma de referencia con la herramienta BWA, obteniendo como resultado un archivo en formato SAM.**

Ejecutar el siguiente comando de alineamiento

    bwa mem -t 4 -M reference.fasta \
    muestra_R1.fastq.gz \
    muestra_R2.fastq.gz \
    > muestra.sam

bwa mem ../../GCF_000233375.1_ICSASG_v2_genomic.fna SRR2006763_1.fastq SRR2006763_2.fastq > SRR2006763.sam

Inspeccionar el archivo .sam de salida con:

    less SRR2006763.sam

**Conversión del archivo SAM a BAM

    samtools view -Sb -q 30 SRR2006763.sam > SRR2006763.bam
    
    
**Ordenar lecturas alineadas por posición**

    samtools sort SRR2006763.bam -o SRR2006763.sort.bam

**Indexación con Samtools**

    samtools index SRR2006763.sort.bam
    
### REFERENCIAS

Pham-Quoc, C., Kieu-Do, B., & Thinh, T. N. (2019). A high-performance FPGA-based BWA-MEM DNA sequence alignment. Wiley, 1-12.
Li, H., & Durbin, R. (2009). Fast and accurate short read alignment with Burrows-Wheeler Transform. Bioinformatics, 1754-60.
JHU. (2016). Johns Hopkins University. Obtenido de Manual of Bowtie 2 - Fast and sensitive read alignment: http://bowtie-bio.sourceforge.net/bowtie2/manual.shtml




