---
title: "Introducción al análisis de secuencias NGS  - Alineamiento"
subtitle: 'Curso Genética y Genómica en Producción Animal'
author:
 name: Dr. José A. Gallardo, Dr(c) Margarita Rivera.
 affiliation: Pontificia Universidad Católica de Valparaíso
 email: <jose.gallardo@pucv.cl>
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
    code_folding: hide
  word_document: default
  pdf_document: default
---

<style>
#TOC {
  color: black;
  font-familiy: Calibri;
  font-size: 14px;
  border-color: #708090; 
}
body {
   color: black;
   font-familiy: Calibri;
}

pre {
  color: black;
  background-color: #F8F8FF;
}
# header {
  color: #800000;
  font-familiy: Calibri;
  background-color: #F5F5F5;
  opacity: 0.8;
  font-size: 16px;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## INTRODUCCIÓN

Uno de los principales usos de la secuenciación de próxima generación es descubrir variaciones entre grandes poblaciones de muestras relacionadas (Danecek et al., 2011), con este fin, se han desarrollado tuberías que incluyen el procesamiento de grandes volúmenes de datos, y dentro de las cuales, constan los pasos de alineamiento y llamado de variantes. Uno de los softwares más empleados para realizar este último paso, es GATK, que se comprende como un kit de herramientas de análisis del genoma desarrollados por el Broad Institute, que tiene la capacidad de realizar gran parte del análisis requerido para llamar variantes genómicas (Deatherage, 2020).


Por otro lado, posterior al llamado de variantes se usan otros softwares en conjunto, que permiten realizar anotaciones de las mismas, como es el caso de SnpEff, que es una herramienta de predicción de efectos y anotaciones de variantes, como cambios de aminoácidos (Cingolani, y otros, 2012) o anotaciones de una variedad de modelos de genes codificantes y no codificantes de proteínas de una variedad de especies (Liu, y otros, 2015).

El presente trabajo tiene por objeto realizar el llamado de variantes y la anotación de una muestra secuenciada mediante el uso de GATK, Snpeff y otras herramientas de anotación y visualización de la región blanco.


### FORMATO VCF



### SOFTWARES DE BIOINFORMÁTICA

(GATK)[https://gatk.broadinstitute.org/hc/en-us] presenta ventajas para el llamado de variantes, como, la integración de evidencia de variantes de múltiples muestras con genotipado conjunto, permite el uso de polimorfismos de un solo nucleótido (SNP) e Indels validados para mejorar la precisión de la llamada de variante y sus métodos se implementan de una manera susceptible a lecturas que se originan en una variedad de preparación de plantillas (McCormick, Truong, & Mullet, 2015). Sin embargo y aunque, como se ha visto, la precisión de esta tubería ya es alta, los falsos positivos (FP) siguen siendo inevitables, por lo que, después de la llamada de variantes, se recomienda filtrar los FP como parte de las buenas prácticas del software (Tan, Zhang, Yang, & Yin, 2020).

### Objetivos del trabajo práctico


### Origen de las muestras



### Etapas del alineamiento.



### Actividades

### 1 - Conectar a servidor Pomeo

Conecte al servidor pomeo usando la siguiente dirección IP: **200.54.220.141** puerto 22.

Para Windows puede conectarse con el software PuTTy y las claves de acceso dadas en la primera clase.


### 2 - Configurar bioconda e instalar programas para análisis

Para configurar el canal bioconda se debe ejecutar el siguiente comando

    conda config --add channels bioconda
    
Instalar los software bwa
   
    conda install -c bioconda bwa
        
Instalar samtools requiere un proceso de instalación un poco más largo, siga cada paso con atención.
    
    conda install -c bioconda samtools
    
    conda config --add channels bioconda 

    conda config --add channels conda-forge 

    conda install samtools==1.11


### 3 - Verificar directorios de instalación

Si desea constatar la ruta de instalación de un programa determinado puedes colocar el comando "whereis" en la terminal más el programa del que desea obtener la ruta.

     whereis sratoolkit 
     whereis samtools
     whereis bwa 

La salida de cada comando indicará la ruta de instalación como sigue, para cada programa del que desees obtener información.

    /home2/usuario/miniconda3/bin/bwa
     
### 4 - Creación de directorio de trabajo y descarga de datos para alineamiento




### 5 - Indexación del genoma de referencia


### 6 - Alineamiento


  


    
### 7 - VISUALIZACIÓN DE ALINEAMIENTOS


**Algunas observaciones adicionales**



### REFERENCIAS



